Main svc admin/categories
StanislavFishkov/java-explore-with-me-plus pull request #24
Opened 2024-10-17 19:44 UTC by amartynsh

2024-10-17 20:36 UTC, StanislavFishkov requested changes

2024-10-17 20:36 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/categories/countroller/AdminCategoriesController.java
> +    public Category updateCategory(@PathVariable("id") long id, @Valid @RequestBody CategoryDto categoryDto) {
long id -> Long id. Та же история, что Елене писал. Думаю стоит делать всем одинаково, раз уже начали.

2024-10-17 20:36 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/categories/dto/CategoryDto.java
> +    @NotNull(message = "Категория не может быть пустой")
@NotBlank включает в себя условие, что поле не равно null. То есть @NotNull можно убрать.

2024-10-17 20:36 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/categories/service/CategoriesServiceImpl.java
> +    }
Нет проверки на уникальность имени категории. В swagger прописано это условие явно.

2024-10-17 20:36 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/categories/service/CategoriesServiceImpl.java
> +        }
Не уверен, что тут нужна проверка на существование. Главный результат после delete, что такой записи больше нет. Если её уже не было, не уверен, что нужна ошибка. Но это от проверок зависит, конечно.

2024-10-17 20:36 UTC, StanislavFishkov commented on main-service/src/main/resources/schema.sql
> +    CONSTRAINT categories_unique UNIQUE (name)
А, проверка вот тут на уникальность. Тогда, наверное, можно не проверять перед. Хотя обычно стараются не писать в базу, если можно проверить заранее.

2024-10-17 20:38 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/categories/service/CategoriesServiceImpl.java
> +    public final CategoriesRepository categoriesRepository;
Почему public?

2024-10-17 20:40 UTC, amartynsh commented on main-service/src/main/java/ru/practicum/ewm/categories/service/CategoriesServiceImpl.java
> +    }
В БД констреин прпоисан на уникальность имени

2024-10-17 20:52 UTC, StanislavFishkov submitted a review, later dismissed

2024-10-18 03:54 UTC, Elen-B requested changes

2024-10-18 03:54 UTC, Elen-B commented on main-service/src/main/java/ru/practicum/ewm/categories/countroller/AdminCategoriesController.java
> +    @ResponseStatus(HttpStatus.OK)
по сваггеру нужно возвращать код 204 HttpStatus.NO_CONTENT, в постман тестах это проверяется

2024-10-18 03:54 UTC, Elen-B commented on main-service/src/main/java/ru/practicum/ewm/categories/service/CategoriesServiceImpl.java
> +    public Category addCategory(CategoryDto categoryDto) {
@Transactional не надо тут?

2024-10-18 04:05 UTC, Elen-B approved these changes

2024-10-18 08:31 UTC, Elen-B approved these changes

2024-10-18 08:32 UTC, StanislavFishkov approved these changes

2024-10-18 08:33 UTC, merged