Первый коммит по функционалу events/private
StanislavFishkov/java-explore-with-me-plus pull request #26
Opened 2024-10-18 19:33 UTC by amartynsh

2024-10-18 19:37 UTC, amartynsh commented
Коммит что бы не задерживать коллег.
Нереализовано 2 метода т.к. необходимо доп. функционал:
GET /users/{userId}/events/{eventId}/requests 
Получение информации о запросах на участие в событии текущего пользователя

PATCH
/users/{userId}/events/{eventId}/requests
Изменение статуса (подтверждена, отменена) заявок на участие в событии текущего пользователя

Так же update не до конца работает  (проходит 3 из 4 теста)

2024-10-19 04:15 UTC, Elen-B submitted a review, later dismissed

2024-10-19 13:26 UTC, StanislavFishkov requested changes

2024-10-19 13:26 UTC, StanislavFishkov commented on main-service/src/main/resources/schema.sql
> +	state_action text NULL,
Это лишнее поле, его не надо хранить в базе - оно только в dto используется. От него надо логику построить.

2024-10-19 13:26 UTC, StanislavFishkov commented on main-service/src/main/resources/schema.sql
> +	CONSTRAINT fk_location FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE CASCADE
Тоже public надо убрать.

2024-10-19 13:26 UTC, StanislavFishkov commented on main-service/src/main/resources/schema.sql
> +	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
Я бы предложил использовать везде одинаковые названия типов, а то я запутался между BIGINT и INT8. Мне кажется, не очень хорошо называть в одной схеме базы одно и тоже по-разному. Тоже самое и про int4, bool.

Из документации postgres: SQL only specifies the integer types integer (or int), smallint, and bigint. The type names int2, int4, and int8 are extensions, which are also used by some other SQL database systems.
https://www.postgresql.org/docs/current/datatype-numeric.html

2024-10-19 13:26 UTC, StanislavFishkov commented on main-service/src/main/resources/schema.sql
> +	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
И не понимаю зачем вот это нужно: ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL

2024-10-19 13:26 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventResponseDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
А почему тут паттерн не из utils? Который у тебя в других DTO @JsonFormat(pattern = DateTimeUtil.DATE_TIME_FORMAT).

2024-10-19 13:26 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventUpdateDto.java
> +
Лишняя пустая строка.

2024-10-19 13:26 UTC, StanislavFishkov commented on main-service/src/main/resources/schema.sql
> +lon decimal NOT NULL,
Думаю стоит указать размерность DECIMAL(9,6)
https://sky.pro/wiki/sql/kakoy-tip-dannykh-vybrat-dlya-khraneniya-koordinat-v-sql/

2024-10-19 13:26 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/event/model/Location.java
> +    private Double lon;
По идее тут BigDecimal нужно брать, так как decimal в postgress - это BigDecimal в java: https://stackoverflow.com/questions/46081023/whats-the-java-data-type-correspondent-to-postgresqls-decimal-in-jpa

С double может быть потеря точности, что нехорошо при работе с координатами.

2024-10-19 13:30 UTC, amartynsh commented on main-service/src/main/resources/schema.sql
> +CREATE TABLE public.events (
когда экспортил из DBEAVER забыл добавить.

2024-10-19 13:33 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/event/model/EventStates.java
> +}
Тут вот такие статусы должны быть, мне Published не хватило в запросах, поэтому изменил у себя:
public enum EventStates {
    PENDING,
    CANCELED,
    PUBLISHED
}

2024-10-19 13:36 UTC, amartynsh commented on main-service/src/main/resources/schema.sql
> +	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
экспорт из DVEAVER, не поправил

2024-10-19 13:41 UTC, amartynsh commented on main-service/src/main/java/ru/practicum/ewm/event/model/Location.java
> +    private Double lon;
В практическом смысле не может. В даблы помещается вплоть до секунд и еще остается в запасе.

2024-10-19 13:46 UTC, amartynsh commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventResponseDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Так проверил как работает :) Потом приведу к одному виду.

2024-10-19 13:58 UTC, StanislavFishkov approved these changes

2024-10-19 14:25 UTC, Elen-B approved these changes

2024-10-19 14:25 UTC, merged