Main svc
StanislavFishkov/java-explore-with-me-plus pull request #34
Opened 2024-10-21 13:05 UTC by StanislavFishkov

2024-10-22 19:03 UTC, z8q requested changes

2024-10-22 19:03 UTC, z8q commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventAdminFilterParamsDto.java
> +    LocalDateTime rangeEnd;
похоже тут поля тоже можно сделать приватными

2024-10-22 19:03 UTC, z8q commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventAdminFilterParamsDto.java
> +    LocalDateTime rangeEnd;
в EventPublicFilterParamsDto тоже

2024-10-22 19:16 UTC, StanislavFishkov commented on main-service/pom.xml
> +            <version>${querydsl.version}</version>
Исправил. А <classifier>jakarta</classifier> - тоже достаточно в главном помнике указать только?

2024-10-22 19:19 UTC, StanislavFishkov commented on main-service/pom.xml
> +                <version>1.1.3</version>
Готово.

2024-10-22 19:24 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/categories/service/CategoriesServiceImpl.java
> +    }
Исправил. Да, так красиво, хотя не уверен, что читаемость улучшаешься)

2024-10-22 19:29 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +@ToString
Да, точно, поэтому @Data убрали, а @String при этом оставили.. А можно, например, так?
@ToString(onlyExplicitlyIncluded = true) на класс
и
@ToString.Include только на id
private Long id;

2024-10-22 19:31 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +    EventMapper eventMapper;
Тут исправил. А в чем плюс от того, чтобы явно задать private и final? Мне кажется, читаемость лучше, когда сразу понятно какие модификаторы стоят на переменных.

2024-10-22 19:34 UTC, StanislavFishkov commented on main-service/src/main/java/ru/practicum/ewm/event/dto/EventAdminFilterParamsDto.java
> +    LocalDateTime rangeEnd;
Поставил на оба класса: @FieldDefaults(level = AccessLevel.PRIVATE)

До сих пор не пойму мне так больше нравится, чем явное указание, или нет)

2024-10-23 17:04 UTC, z8q approved these changes

2024-10-23 17:28 UTC, merged